//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace TrainingJournal
{
    public partial class TrainJournal : INotifyPropertyChanged
    {
        private string _name;
        private int _numOfSets;
        private int _numOfReps;
        private int _weight;
        private string _comment;

        public int Identificator { get; set; }

        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
                OnPropertyChanged();
            }
        }

        public string Login { get; set; }
        public System.DateTime Date { get; set; }

        public int NumOfSets
        {
            get
            {
                return _numOfSets;
            }
            set
            {
                _numOfSets = value;
                OnPropertyChanged();
            }
        }

        public int NumOfReps
        {
            get
            {
                return _numOfReps;
            }
            set
            {
                _numOfReps = value;
                OnPropertyChanged();
            }
        }

        public int Weight
        {
            get
            {
                return _weight;
            }
            set
            {
                _weight = value;
                OnPropertyChanged();
            }
        }

        public string Comment
        {
            get
            {
                return _comment;
            }
            set
            {
                _comment = value;
                OnPropertyChanged();
            }
        }

        public virtual User User { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;
        public void OnPropertyChanged([CallerMemberName]string prop = "")
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(prop));
        }
    }
}
