//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingJournal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainJournalEntities : DbContext
    {
        public TrainJournalEntities()
            : base("name=TrainJournalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C1RPmax> C1RPmax { get; set; }
        public virtual DbSet<ChestTable> ChestTables { get; set; }
        public virtual DbSet<NeckTable> NeckTables { get; set; }
        public virtual DbSet<TrainJournal> TrainJournals { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Weight> Weights { get; set; }
        public virtual DbSet<ArmTable> ArmTables { get; set; }
        public virtual DbSet<HipTable> HipTables { get; set; }
        public virtual DbSet<ShinTable> ShinTables { get; set; }
        public virtual DbSet<WaistTable> WaistTables { get; set; }
    }
}
