//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAntropometry
    {
        public int Identificator { get; set; }
        public string Login { get; set; }
        public Nullable<float> Nech { get; set; }
        public Nullable<float> Chest { get; set; }
        public Nullable<float> Arm { get; set; }
        public Nullable<float> Waist { get; set; }
        public Nullable<float> Hip { get; set; }
        public Nullable<float> Shin { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual User User { get; set; }
    }
}
